# /// script
# dependencies = [
#     "packaging",
#     "tomli",
# ]
# ///
"""Generate requirements-min.txt for testing minimum dependency versions."""

from itertools import chain
from pathlib import Path

from packaging.requirements import Requirement
from tomli import load as toml_load

HEADER = (
    "# Do not edit this file. It is automatically generated by the script\n"
    "# /environments/make-min-deps.py using the dependencies specified in\n"
    "# pyproject.toml.\n"
)

if __name__ == "__main__":
    # load the pyproject.toml file
    with Path("./pyproject.toml").open("rb") as f:
        pyproject = toml_load(f)

    # extract dependencies, optionals, and dev group from pyproject.toml
    deps = [Requirement(d) for d in pyproject["project"]["dependencies"]]
    optionals = pyproject["project"]["optional-dependencies"].values()
    deps.extend({Requirement(o) for o in chain.from_iterable(optionals)})
    reqs = [f"{dep.name}=={next(iter(dep.specifier)).version}.*" for dep in deps]
    reqs.extend(pyproject["dependency-groups"]["dev"])

    # write the requirements as to file on disk
    text = HEADER + "\n".join(sorted(reqs)) + "\n"
    with Path("./requirements-min.txt").open("w") as f:
        f.writelines(text)
