name: Propose a feature
description: Propose an enhancement before opening a pull request to add it
labels: enh
body:
  - type: markdown
    attributes:
      value: "Thanks for using OSMnx!"

  - type: checkboxes
    id: contributing
    attributes:
      label: Contributing guidelines
      description: Before you proceed, read the [contributing guidelines](../blob/main/CONTRIBUTING.md) regarding where to ask usage questions and how to propose a feature.
      options:
        - label: I understand the contributing guidelines
          required: true

  - type: checkboxes
    id: documentation_examples
    attributes:
      label: Documentation
      description: Before you proceed, review the [documentation](https://osmnx.readthedocs.io/) and [OSMnx examples](https://github.com/gboeing/osmnx-examples) gallery, which cover key concepts, installation, and package usage.
      options:
        - label: My proposal is not addressed by the documentation or examples
          required: true

  - type: checkboxes
    id: existing_issue
    attributes:
      label: Existing issues
      description: Before you proceed, search the open/closed issues and pull requests to see if anything similar has been proposed.
      options:
        - label: Nothing similar appears in an existing issue
          required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does your feature proposal solve?
      description: Provide a clear and concise description of your use case and the current problem, challenge, or limitation.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What is your proposed solution?
      description: Provide a clear and concise description of what you want to change in OSMnx and how you plan to implement it.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives have you considered?
      description: Provide a clear and concise description of any alternative solutions, features, or workarounds you have considered.
    validations:
      required: true

  - type: textarea
    id: mwe
    attributes:
      label: Additional context
      description: Provide a complete minimal working example of code to demonstrate your use case. Add any additional code snippets, context, or screenshots about the feature proposal to demonstrate its importance and feasibility.
    validations:
      required: true
