version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

formats: all

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
