name: Build and push docker images

env:
  OWNER: ${{ github.repository_owner }}

on: [push]
jobs:
  amd64-base:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      platform: amd64
      resulting_tag: 'latest'
      jupyter_tag: 'latest'
  aarch64-base:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      platform: arm64
      resulting_tag: 'aarch64-latest'
      jupyter_tag: 'aarch64-latest'
