name: Build and push docker images

env:
  OWNER: ${{ github.repository_owner }}

on: [push]
jobs:
  amd64-base:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "./environments/docker"
          push: false
          platforms: amd64
          tags: ${{ env.OWNER }}/osmnx:latest
  aarch64-base:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "./environments/docker"
          push: false
          platforms: arm64
          tags: ${{ env.OWNER }}/osmnx:aarch64-latest
