name: Test minimal versions

on:
  schedule:
    - cron: "0 4 * * 1" # every monday at 04:00 UTC
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install OSMnx
        run: |
          python -m pip install -r ./environments/tests/requirements-test-minimal.txt
          python -m pip install -e .
          python -m pip list -v
          python -m pip show osmnx
          python --version

      - name: Test code
        run: pytest --verbose --maxfail=1
